### ISSUE TITLE
HTTP Error

### ISSUE THREAD

**Issue by yuzhong1997** [ChristopherWilks/snaptron-experiments#7]
Hi,

I recently found whichever commands I used for querying from the server, and it turned out "HTTP Error 308: Permanent Redirect".
i.e. python client/query_snaptron.py --query-file data/alk_alt_tss.hg19.snap.tsv --datasrc srav1 --function jir | wc -l  
OR
./qs --region "BRCA1" --contains 1 --filters "samples_count>=100&annotated=1"

Thanks.

Yu

**Comment by ChristopherWilks** [comment]
should be fixed now in an update I just pushed today, do a git pull and try again

**Comment by yuzhong1997** [comment]
WOW! Thanks! Actually I just figured it out due to https issue and made a change on my local. But you just updated! Thanks man.
